version: '3.8'

services:
  backend:
    build: .
    ports:
      - '8080:8080'
    depends_on:
      - postgres

  postgres:
    image: 'postgres:13'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: dog_catcher
    volumes:
      - 'postgres_data:/var/lib/postgresql/data'
    ports:
      - "5432:5432"

volumes:
  postgres_data: